stages:
  - security

services:
  - docker:dind

Insecure Container:
  stage: security
  image: docker:stable
  tags:
    - gitlab-runner
  script:
    - docker build -t insecure_container .
    - docker run 
      --env accessKeyId=${accessKeyId} 
      --env accessKeySecret=${accessKeySecret} 
      --env apiUrl=${apiUrl}
        insecure_container /bin/bash /vulnerabilities.sh

Secure Container:
  stage: security
  image: docker:stable
  tags:
    - gitlab-runner
  script:
    - docker build -t secure_container .
    - docker run 
      --env accessKeyId=${accessKeyId} 
      --env accessKeySecret=${accessKeySecret} 
      --env apiUrl=${apiUrl}
        secure_container /bin/bash -c "yum update -y && bash /vulnerabilities.sh"